<a href="https://colab.research.google.com/github/Tuevu110405/Module5_1st_step_toDL/blob/feature%2Foptimizer/optimizer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as np

f(w1, w2) = 0.1w_1^2+2w_2^2

In [9]:
def f(w1, w2):
    return 0.1*w1**2+2*w2**2

In [12]:
def df_w(W):
    """"
    Thuc hien tinh gradient cua dw1 va dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW-- np.array [dw1, dw2]
    """
    w1, w2 = W
    dw1 = 0.2*w1
    dw2 = 4*w2
    dw = np.array([dw1, dw2])
    return dw

In [13]:
def sgd(W, dw, lr):
    W -= lr*dw
    return W

In [14]:
def train_p1(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype = np.float32)
    results = [W]
    for epoch in range(epochs):
        dw = df_w(W)
        W = optimizer(W, dw, lr)
        results.append(W)
    return results

In [16]:
w = train_p1(sgd,0.4, 30)
print(w)

[array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.421478e-07], dtype=float32), array([-4.098310e-01, -4.42

In [ ]:
"""Với bài tập Gradient Descent: câu (a) tại epoch = 2 sau khi áp dụng Gradient Descent ta thu
được w1 và w2 là (Kết quả có thể không chính xác hoàn toàn các bạn chọn kết quả làm tròn gần
nhất)
(A). -4.232, -0.72 (B). -4.232, -0.83
(C). -4.232, -0.94 (D). -4.232, -0.75:"""

w = train_p1(sgd,0.0001, 2)
print(w[-1])

[-5.0002003 -2.0016003]


Bai 2

In [25]:

def gdmomentum(W, lr, epoch, beta):
    v_t = 0
    v_t_1 = 0
    for t in range(epoch):
        dw = df_w(W)
        v_t = beta*v_t-1 + (1-beta)*dw
        W -= v_t* lr
        v_t_1 = v_t
    return W



In [29]:
def gdmomentum(W, lr, epochs, beta):
    v_t = 0  # Initialize momentum term outside the loop
    for t in range(epochs):
        dw = df_w(W)
        v_t = beta * v_t + (1 - beta) * dw  # Correct momentum update
        W -= lr * v_t
    return W

In [30]:
def train_p2(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype = np.float32)
    results = [W]
    for epoch in range(epochs):
        dw = df_w(W)
        W = optimizer(W,lr,epochs, 0.5)
        results.append(W)
    return results



In [34]:
train_p2(optimizer = gdmomentum, lr = 0.06, epochs =30)

[array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.000122,  0.      ], dtype=float32),
 array([-0.00

RMSprop

In [47]:
def rmsprop(W, lr, gamma, epoch, epsilon):

    s_t = 0
    for i in range(epoch):
        dw = df_w(W)
        s_t = gamma* s_t + (1-gamma) * (dw**2)
        W -= lr*dw/np.sqrt(s_t +epsilon)

    return W

In [48]:
def train_p2(optimizer, lr, epochs):
    W = np.array([-5, -2], dtype = np.float32)
    results = [W]
    for epoch in range(epochs):
        dw = df_w(W)
        W = optimizer(W,lr,0.9,epochs, 10**(-6))
        results.append(W)
    return results

In [51]:
train_p2(optimizer = rmsprop, lr = 0.03, epochs = 30)

[array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.03041785], dtype=float32),
 array([-0.00739032,  0.0304178

Adam

In [19]:
def adam(W, lr, beta1, beta2, epoch, epsilon):
    m_t_1 = 0
    v_t_1 = 0
    for i in epoch:
        dw = df_w(W)
        m_t = beta1*m_t + (1-beta1)*dw
        v_t = beta2*v_t + (1-beta2)*(dw**2)
        m_t_hat = m_t/(1-beta1**i)
        v_t_hat = v_t/(1-beta2**i)
        W -= lr*m_t_hat/(np.sqrt(v_t_hat)+epsilon)

    return W
